// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lm_mcmc_cpp
List lm_mcmc_cpp(List X_ipd, List y_ipd, List X_ad, List Z_ad, List drm_ad, List V_ad, List beta_tilde, List reported, NumericVector hat_tau, NumericVector hat_gamma, NumericMatrix theta_ipd0, NumericMatrix theta_ad0, List beta_ad0, NumericMatrix alpha0, NumericVector tau0, LogicalVector extra_theta, NumericVector mu0, NumericMatrix Sigma0, double sig2, NumericMatrix invLambda, NumericMatrix Phi0, int n_iter, int burnin, double step_theta, double step_alpha, double step_tau, double nu0, bool use_drm, int drm_cov_col, bool verbose);
RcppExport SEXP _bayesmetaipd_lm_mcmc_cpp(SEXP X_ipdSEXP, SEXP y_ipdSEXP, SEXP X_adSEXP, SEXP Z_adSEXP, SEXP drm_adSEXP, SEXP V_adSEXP, SEXP beta_tildeSEXP, SEXP reportedSEXP, SEXP hat_tauSEXP, SEXP hat_gammaSEXP, SEXP theta_ipd0SEXP, SEXP theta_ad0SEXP, SEXP beta_ad0SEXP, SEXP alpha0SEXP, SEXP tau0SEXP, SEXP extra_thetaSEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP sig2SEXP, SEXP invLambdaSEXP, SEXP Phi0SEXP, SEXP n_iterSEXP, SEXP burninSEXP, SEXP step_thetaSEXP, SEXP step_alphaSEXP, SEXP step_tauSEXP, SEXP nu0SEXP, SEXP use_drmSEXP, SEXP drm_cov_colSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X_ipd(X_ipdSEXP);
    Rcpp::traits::input_parameter< List >::type y_ipd(y_ipdSEXP);
    Rcpp::traits::input_parameter< List >::type X_ad(X_adSEXP);
    Rcpp::traits::input_parameter< List >::type Z_ad(Z_adSEXP);
    Rcpp::traits::input_parameter< List >::type drm_ad(drm_adSEXP);
    Rcpp::traits::input_parameter< List >::type V_ad(V_adSEXP);
    Rcpp::traits::input_parameter< List >::type beta_tilde(beta_tildeSEXP);
    Rcpp::traits::input_parameter< List >::type reported(reportedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hat_tau(hat_tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hat_gamma(hat_gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type theta_ipd0(theta_ipd0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type theta_ad0(theta_ad0SEXP);
    Rcpp::traits::input_parameter< List >::type beta_ad0(beta_ad0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type extra_theta(extra_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type invLambda(invLambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Phi0(Phi0SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< double >::type step_theta(step_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type step_alpha(step_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type step_tau(step_tauSEXP);
    Rcpp::traits::input_parameter< double >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< bool >::type use_drm(use_drmSEXP);
    Rcpp::traits::input_parameter< int >::type drm_cov_col(drm_cov_colSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_mcmc_cpp(X_ipd, y_ipd, X_ad, Z_ad, drm_ad, V_ad, beta_tilde, reported, hat_tau, hat_gamma, theta_ipd0, theta_ad0, beta_ad0, alpha0, tau0, extra_theta, mu0, Sigma0, sig2, invLambda, Phi0, n_iter, burnin, step_theta, step_alpha, step_tau, nu0, use_drm, drm_cov_col, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sim1_mcmc_cpp
List sim1_mcmc_cpp(List X_ipd, NumericMatrix Y_ipd, List X_ref, List Z_ref, NumericMatrix beta_tilde, List V_list, IntegerVector idx_t1, IntegerVector idx_t2, IntegerVector idx_t3, NumericMatrix theta_ipd0, NumericMatrix theta_ad0, NumericMatrix beta_ad0, NumericVector mu0, NumericMatrix Sigma0, double sig2, NumericVector tau0, NumericMatrix alpha0, NumericVector hat_tau, NumericVector hat_gamma, NumericMatrix invLambda, NumericMatrix Phi0, int n_iter, int burnin, double step_theta, double step_alpha, double step_tau, double nu0, bool verbose);
RcppExport SEXP _bayesmetaipd_sim1_mcmc_cpp(SEXP X_ipdSEXP, SEXP Y_ipdSEXP, SEXP X_refSEXP, SEXP Z_refSEXP, SEXP beta_tildeSEXP, SEXP V_listSEXP, SEXP idx_t1SEXP, SEXP idx_t2SEXP, SEXP idx_t3SEXP, SEXP theta_ipd0SEXP, SEXP theta_ad0SEXP, SEXP beta_ad0SEXP, SEXP mu0SEXP, SEXP Sigma0SEXP, SEXP sig2SEXP, SEXP tau0SEXP, SEXP alpha0SEXP, SEXP hat_tauSEXP, SEXP hat_gammaSEXP, SEXP invLambdaSEXP, SEXP Phi0SEXP, SEXP n_iterSEXP, SEXP burninSEXP, SEXP step_thetaSEXP, SEXP step_alphaSEXP, SEXP step_tauSEXP, SEXP nu0SEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X_ipd(X_ipdSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y_ipd(Y_ipdSEXP);
    Rcpp::traits::input_parameter< List >::type X_ref(X_refSEXP);
    Rcpp::traits::input_parameter< List >::type Z_ref(Z_refSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta_tilde(beta_tildeSEXP);
    Rcpp::traits::input_parameter< List >::type V_list(V_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_t1(idx_t1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_t2(idx_t2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_t3(idx_t3SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type theta_ipd0(theta_ipd0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type theta_ad0(theta_ad0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta_ad0(beta_ad0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hat_tau(hat_tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hat_gamma(hat_gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type invLambda(invLambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Phi0(Phi0SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< double >::type step_theta(step_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type step_alpha(step_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type step_tau(step_tauSEXP);
    Rcpp::traits::input_parameter< double >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sim1_mcmc_cpp(X_ipd, Y_ipd, X_ref, Z_ref, beta_tilde, V_list, idx_t1, idx_t2, idx_t3, theta_ipd0, theta_ad0, beta_ad0, mu0, Sigma0, sig2, tau0, alpha0, hat_tau, hat_gamma, invLambda, Phi0, n_iter, burnin, step_theta, step_alpha, step_tau, nu0, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bayesmetaipd_lm_mcmc_cpp", (DL_FUNC) &_bayesmetaipd_lm_mcmc_cpp, 30},
    {"_bayesmetaipd_sim1_mcmc_cpp", (DL_FUNC) &_bayesmetaipd_sim1_mcmc_cpp, 28},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayesmetaipd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
