# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_mcmc_cpp <- function(X_ipd, y_ipd, X_ad, Z_ad, drm_ad, V_ad, beta_tilde, reported, hat_tau, hat_gamma, theta_ipd0, theta_ad0, beta_ad0, alpha0, tau0, extra_theta, mu0, Sigma0, sig2, invLambda, Phi0, n_iter, burnin, step_theta, step_alpha, step_tau, nu0, use_drm, drm_cov_col, verbose) {
    .Call(`_bayesmetaipd_lm_mcmc_cpp`, X_ipd, y_ipd, X_ad, Z_ad, drm_ad, V_ad, beta_tilde, reported, hat_tau, hat_gamma, theta_ipd0, theta_ad0, beta_ad0, alpha0, tau0, extra_theta, mu0, Sigma0, sig2, invLambda, Phi0, n_iter, burnin, step_theta, step_alpha, step_tau, nu0, use_drm, drm_cov_col, verbose)
}

sim1_mcmc_cpp <- function(X_ipd, Y_ipd, X_ref, Z_ref, beta_tilde, V_list, idx_t1, idx_t2, idx_t3, theta_ipd0, theta_ad0, beta_ad0, mu0, Sigma0, sig2, tau0, alpha0, hat_tau, hat_gamma, invLambda, Phi0, n_iter, burnin, step_theta, step_alpha, step_tau, nu0, verbose) {
    .Call(`_bayesmetaipd_sim1_mcmc_cpp`, X_ipd, Y_ipd, X_ref, Z_ref, beta_tilde, V_list, idx_t1, idx_t2, idx_t3, theta_ipd0, theta_ad0, beta_ad0, mu0, Sigma0, sig2, tau0, alpha0, hat_tau, hat_gamma, invLambda, Phi0, n_iter, burnin, step_theta, step_alpha, step_tau, nu0, verbose)
}

